#!/usr/bin/env zsh

{

# Clean all dot files
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for file in $(cd $DIR/dotfiles && echo .*); do
  rm ~/$file
done;

# Clean created directories
rm -rf ~/.{vim,tmux,bin,zsh_plugins.sh}

}
