#!/usr/bin/env zsh

{

# Install tmux plugins. You need Tmux >= 1.9. prefix, I to install plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Install vim Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Install antibody
mkdir -p ~/.bin
curl -sfL git.io/antibody | sudo sh -s - -b ~/.bin

}
